package main

// Adversarial test cases generated by a separate LLM to stress-test
// the sanitize/sanitizeFilename pipeline. These complement the main
// test suite in sanitize_test.go.

import "testing"

func TestSanitizeAdversarial(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		want    string
		wantErr bool
	}{
		// ====================================================================
		// 1. Unicode & Normalization Edge Cases
		// ====================================================================
		{
			name:  "Unicode: Zero-width joiner between valid chars",
			input: "a\u200Db",
			want:  "a-b",
		},
		{
			name:  "Unicode: Standalone byte order mark (BOM)",
			input: "\uFEFF",
			want:  "",
		},
		{
			name:  "Unicode: BOM prepended to a valid string",
			input: "\uFEFFabc",
			want:  "abc",
		},
		{
			name:  "Unicode: Right-to-left mark (RTL) injection",
			input: "a\u200Fb",
			want:  "a-b",
		},
		{
			name:  "Unicode: Isolated combining accent mark (no base)",
			input: "\u0300",
			want:  "",
		},
		{
			name:  "Unicode: Valid character with attached combining accent (NFC)",
			input: "\u00C5", // Å
			want:  "a",
		},
		{
			name:  "Unicode: Decomposed valid character with combining accent (NFD)",
			input: "A\u030A", // A + ring above
			want:  "a",
		},
		{
			name:  "Unicode: Pre-existing replacement character U+FFFD input",
			input: "a\uFFFDb",
			want:  "a-b",
		},
		{
			name:  "Unicode: Overlong UTF-8 sequence (2-byte representation of ASCII 'a')",
			input: "\xC1\x81",
			want:  "",
		},
		{
			name:  "Unicode: Invalid UTF-8 trailing byte sequence",
			input: "abc\x80\x81def",
			want:  "abc-def",
		},
		{
			// In Go, "\xD83D\xDE00" is NOT a surrogate pair — it's bytes
			// D8 '3' 'D' DE '0' '0'. The ill-formed bytes D8/DE become
			// U+FFFD (stripped), leaving ASCII '3','D','0','0'.
			name:  "Unicode: Surrogate halves (invalid standalone in UTF-8)",
			input: "\xD83D\xDE00",
			want:  "3d-00",
		},

		// ====================================================================
		// 2. Special-Case Table Boundaries & Unhandled Latin Scripts
		// ====================================================================
		{
			name:  "Special-Case: Lowercase ł handled",
			input: "łódź",
			want:  "lodz",
		},
		{
			name:  "Special-Case: Uppercase Ł handled",
			input: "ŁÓDŹ",
			want:  "lodz",
		},
		{
			name:  "Special-Case: Lowercase ß handled",
			input: "groß",
			want:  "gross",
		},
		{
			name:  "Special-Case: Uppercase ẞ (Length expansion under ToLower)",
			input: "GROß",
			want:  "gross",
		},
		{
			name:  "Special-Case: Turkish dotless i (ı)",
			input: "ı",
			want:  "i",
		},
		{
			name:  "Special-Case: Thorn (þ)",
			input: "þor",
			want:  "thor",
		},
		{
			name:  "Special-Case: Thorn uppercase (Þ)",
			input: "Þór",
			want:  "thor",
		},
		{
			name:  "Special-Case: Eth (ð) vs barred D (Đ)",
			input: "ðor",
			want:  "dor",
		},
		{
			name:  "Special-Case: Eth uppercase (Ð)",
			input: "Ðor",
			want:  "dor",
		},
		{
			name:  "Special-Case: Kra (ĸ)",
			input: "ĸa",
			want:  "ka",
		},
		{
			name:  "Special-Case: Eng (ŋ)",
			input: "ŋa",
			want:  "nga",
		},
		{
			name:  "Special-Case: Eng uppercase (Ŋ)",
			input: "Ŋa",
			want:  "nga",
		},
		{
			name:  "Special-Case: Long s (ſ)",
			input: "ſal",
			want:  "sal",
		},
		{
			name:  "Special-Case: Capital sharp S (ẞ)",
			input: "ẞee",
			want:  "ssee",
		},
		{
			name:  "Special-Case: Afrikaans n-preceded-by-apostrophe (ŉ)",
			input: "ŉa",
			want:  "na",
		},
		{
			name:  "Special-Case: Barred T (ŧ)",
			input: "ŧa",
			want:  "ta",
		},
		{
			name:  "Special-Case: Barred T uppercase (Ŧ)",
			input: "Ŧa",
			want:  "ta",
		},
		{
			name:  "Special-Case: Dutch IJ ligature (ĳ)",
			input: "ĳsselmeer",
			want:  "ijsselmeer",
		},
		{
			name:  "Special-Case: Dutch IJ ligature uppercase (Ĳ)",
			input: "Ĳsselmeer",
			want:  "ijsselmeer",
		},
		{
			name:  "Special-Case: Catalan middle-dot L (ŀ)",
			input: "ŀa",
			want:  "la",
		},
		{
			name:  "Special-Case: Catalan middle-dot L uppercase (Ŀ)",
			input: "Ŀa",
			want:  "la",
		},
		{
			name:  "Special-Case: Stroked A (Ⱥ)",
			input: "Ⱥ",
			want:  "a",
		},
		{
			name:  "Special-Case: Stroked A lowercase (ⱥ)",
			input: "ⱥbc",
			want:  "abc",
		},
		// African language special cases
		{
			name:  "Special-Case: Schwa (ə)",
			input: "bəkir",
			want:  "bekir",
		},
		{
			name:  "Special-Case: Open E (ɛ)",
			input: "ɛwe",
			want:  "ewe",
		},
		{
			name:  "Special-Case: Open O (ɔ)",
			input: "ɔman",
			want:  "oman",
		},
		{
			name:  "Special-Case: Hooked B (ɓ)",
			input: "ɓa",
			want:  "ba",
		},
		{
			name:  "Special-Case: Hooked D (ɗ)",
			input: "ɗa",
			want:  "da",
		},
		{
			name:  "Special-Case: African D (ɖ)",
			input: "ɖa",
			want:  "da",
		},
		{
			name:  "Special-Case: Hooked K (ƙ)",
			input: "ƙa",
			want:  "ka",
		},
		{
			name:  "Special-Case: Hooked F (ƒ)",
			input: "ƒa",
			want:  "fa",
		},
		// Typographic ligatures
		{
			name:  "Special-Case: Ligature ff (ﬀ)",
			input: "oﬀice",
			want:  "office",
		},
		{
			name:  "Special-Case: Ligature fi (ﬁ)",
			input: "ﬁle",
			want:  "file",
		},
		{
			name:  "Special-Case: Ligature fl (ﬂ)",
			input: "ﬂoor",
			want:  "floor",
		},
		{
			name:  "Special-Case: Ligature ffi (ﬃ)",
			input: "oﬃce",
			want:  "office",
		},
		{
			name:  "Special-Case: Ligature ffl (ﬄ)",
			input: "raﬄe",
			want:  "raffle",
		},
		// Croatian digraphs
		{
			name:  "Special-Case: Croatian DZ digraph (ǆ)",
			input: "ǆa",
			want:  "dza",
		},
		{
			name:  "Special-Case: Croatian LJ digraph (ǉ)",
			input: "ǉa",
			want:  "lja",
		},
		{
			name:  "Special-Case: Croatian NJ digraph (ǌ)",
			input: "ǌa",
			want:  "nja",
		},

		// ====================================================================
		// 3. Go-Specific Case-Folding Quirks
		// ====================================================================
		{
			name:  "Go Quirks: Turkish Dotted I (İ) standard ToLower expansion",
			input: "İSTANBUL",
			want:  "istanbul",
		},

		// ====================================================================
		// 4. Hyphen & Trimming Edge Cases
		// ====================================================================
		{
			name:  "Hyphens: String containing only hyphens",
			input: "-------",
			want:  "",
		},
		{
			name:  "Hyphens: Consecutive internal hyphens collapsing",
			input: "foo----bar",
			want:  "foo-bar",
		},
		{
			name:  "Hyphens: Non-alphanumeric conversion creating duplicates",
			input: "foo#$@bar",
			want:  "foo-bar",
		},
		{
			name:  "Hyphens: Leading and trailing non-alphanumerics trimmed",
			input: "$foo$",
			want:  "foo",
		},
		{
			name:  "Hyphens: Single hyphen input",
			input: "-",
			want:  "",
		},
		{
			name:  "Hyphens: Single valid character",
			input: "a",
			want:  "a",
		},
		{
			name:  "Hyphens: Mixed valid/invalid with leading hyphens",
			input: "!!!a-b!!!",
			want:  "a-b",
		},

		// ====================================================================
		// 5. Adversarial & Malicious Payloads
		// ====================================================================
		{
			name:  "Adversarial: Embedded null byte injection",
			input: "foo\x00bar",
			want:  "foo-bar",
		},
		{
			name:  "Adversarial: ASCII control characters range",
			input: "\u0001\u001Ffoo",
			want:  "foo",
		},
		{
			name:  "Adversarial: Private Use Area (PUA) characters",
			input: "foo\uE000bar",
			want:  "foo-bar",
		},
		{
			name:  "Adversarial: Unassigned Unicode codepoint",
			input: "foo\uFFFFbar",
			want:  "foo-bar",
		},
		{
			name:  "Adversarial: Maximum Unicode codepoint",
			input: "foo\U0010FFFFbar",
			want:  "foo-bar",
		},
		{
			name:  "Adversarial: Cyrillic homoglyph (а looks like Latin a but is not)",
			input: "аb", // First char is Cyrillic 'а'
			want:  "b",
		},

		// ====================================================================
		// 6. Empty / Near-Empty Constraints
		// ====================================================================
		{
			name:  "Empty: Completely empty string",
			input: "",
			want:  "",
		},
		{
			name:  "Empty: Space-only string",
			input: "   ",
			want:  "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := sanitize(tt.input)
			if tt.wantErr {
				if err == nil {
					t.Errorf("sanitize(%q) = %q, want error", tt.input, got)
				}
				return
			}
			if err != nil {
				t.Fatalf("sanitize(%q) returned unexpected error: %v", tt.input, err)
			}
			if got != tt.want {
				t.Errorf("sanitize(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestSanitizeFilenameAdversarial(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		want    string
		wantErr bool
	}{
		// ====================================================================
		// 7. Filename Splitting Gotchas & Dot Manipulation
		// ====================================================================
		{
			name:  "Filename: Standard happy path",
			input: "Report.Txt",
			want:  "report.txt",
		},
		{
			name:  "Filename: Standard dotfile",
			input: ".gitignore",
			want:  ".gitignore",
		},
		{
			// filepath.Ext(".foo.bar") = ".bar", base = ".foo" (non-empty),
			// so this is NOT a dotfile — it's base "foo" + ext "bar"
			name:  "Filename: Dotfile containing multiple dots",
			input: ".foo.bar",
			want:  "foo.bar",
		},
		{
			name:  "Filename: Multiple leading dots on a hidden file",
			input: "..hidden",
			want:  ".hidden",
		},
		{
			name:    "Filename: Sequence consisting entirely of dots",
			input:   "...",
			wantErr: true,
		},
		{
			name:  "Filename: Trailing dot with no extension",
			input: "filename.",
			want:  "filename",
		},
		{
			name:  "Filename: Multiple internal dots in base name",
			input: "daily.log.backup.txt",
			want:  "daily-log-backup.txt",
		},
		{
			name:  "Filename: Extension-only string",
			input: ".txt",
			want:  ".txt",
		},

		// ====================================================================
		// 8. Path Separator Injections
		// ====================================================================
		{
			name:  "Filename: Embedded Unix path separator",
			input: "dir/file.txt",
			want:  "dir-file.txt",
		},
		{
			name:  "Filename: Embedded Windows path separator",
			input: "dir\\file.txt",
			want:  "dir-file.txt",
		},
		{
			name:  "Filename: Relative path traversal sequence",
			input: "../file.txt",
			want:  "file.txt",
		},

		// ====================================================================
		// 9. Contract Enforcement (Accidental Dotfiles & Script Rules)
		// ====================================================================
		{
			name:    "Filename: Non-Latin base with Latin extension",
			input:   "你好.txt",
			wantErr: true,
		},
		{
			name:  "Filename: Latin base with non-Latin extension",
			input: "hello.你好",
			want:  "hello",
		},
		{
			name:    "Filename: Punctuation-only base creating accidental dotfile",
			input:   "!!!.txt",
			wantErr: true,
		},
		{
			name:    "Filename: Non-Latin dotfile that strips entirely",
			input:   ".你好",
			wantErr: true,
		},
		{
			name:  "Filename: Thorn in extension",
			input: "file.þxt",
			want:  "file.thxt",
		},
		{
			name:  "Filename: Thorn in base",
			input: "þor.txt",
			want:  "thor.txt",
		},

		// ====================================================================
		// 10. Whitespace & Boundaries
		// ====================================================================
		{
			name:    "Filename: Empty string input",
			input:   "",
			wantErr: true,
		},
		{
			name:  "Filename: Whitespace before extension dot",
			input: "file   .txt",
			want:  "file.txt",
		},
		{
			name:  "Filename: Whitespace after extension dot",
			input: "file.   txt",
			want:  "file.txt",
		},
		{
			name:  "Filename: Invalid characters in extension",
			input: "file.t*x&t",
			want:  "file.t-x-t",
		},
		{
			name:  "Filename: Adversarial null bytes in base name",
			input: "bad\x00file.exe",
			want:  "bad-file.exe",
		},
		{
			// Base is all spaces → sanitizes to empty → refuse to create
			// accidental dotfile ".txt"
			name:    "Filename: Only spaces in base name with valid extension",
			input:   "   .txt",
			wantErr: true,
		},
		{
			name:  "Filename: Double extensions separated by hyphens",
			input: "file-.txt.bak",
			want:  "file-txt.bak",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := sanitizeFilename(tt.input)
			if tt.wantErr {
				if err == nil {
					t.Errorf("sanitizeFilename(%q) = %q, want error", tt.input, got)
				}
				return
			}
			if err != nil {
				t.Fatalf("sanitizeFilename(%q) returned unexpected error: %v", tt.input, err)
			}
			if got != tt.want {
				t.Errorf("sanitizeFilename(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}
